//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangTrungHieu.SachOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONDATHANG = new HashSet<DONDATHANG>();
        }
        [Key]
        [Required]
        public int MaKH { get; set; }

        [Required(ErrorMessage ="Họ tên không được để trống.")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "Tên tài khoản không được để trống.")]
        [MinLength(5,ErrorMessage ="Tên tài khoản phải có ít nhất 5 ký tự.")]
        public string TaiKhoan { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống.")]
        public string MatKhau { get; set; }

        [Required(ErrorMessage = "Email không được để trống.")]
        [EmailAddress(ErrorMessage ="Email không đúng định dạng.")]
        public string Email { get; set; }
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được để trống.")]
        public string DienThoai { get; set; }

        [Required(ErrorMessage = "Ngày sinh không được để trống.")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANG { get; set; }
    }
}
